// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

/*
* This was auto generated by Unreal it came with the errors that are highlighted.
* The only ines that were added were the virtual void functions
* 
* Following the instructons on canvas produced this and I have not been able to find a fix yet.
*/

#include "CoreMinimal.h"
#include "Weapon.h"
#include "AssaultWeapon.generated.h"

UCLASS()
class TOPDOWNSHMUP_API AAssaultWeapon : public AWeapon
{
	GENERATED_BODY()

	virtual void OnStartFire() override;
	virtual void OnStopFire() override;
};
